//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityControl.xUnit.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityControl.xUnit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] decryptedFile {
            get {
                object obj = ResourceManager.GetObject("decryptedFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] encryptedFile {
            get {
                object obj = ResourceManager.GetObject("encryptedFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu u/7DdFX+9TN4AB1U0RCOcVPcgo8qBtP0dqFO1E/0j5zKYnHocRvl6+ci6eKSdUQn3zX5PN/Z7qf1/1BNWlkMhQReeFal83UVOSzS9pO8tT288E59s4bmNd89fNh1CnlKSIxd7xP2aFnJBCX0zeSLaKAneQNPQirOMxuGdJlm9XY+/YFaRXGjJlv4dzzpezgRUCyCC43Ejp7HjvULdL7Or3cjhmOFX4n0Pb7TBUEsAj2odgg37Emz6qd/uc05WZSuMFf7o4/ywJ0sV/9sIOVFWkCe9QjAJXIqm5K8iFO5E0TnOJDvpmZGIT8Z0Qlm7Wwfmu66on9qhHQ7Aht/BIW/KXX+sEM8snQYzbXfqfUqvcmhX1xNhLSLEv5lQ1357gzqknL218Uq9qyjsYq46yCykqnKRmsccxiw7yPIZgexO3KmSy+8eaGrVqVurmI+sOIQKOT2T8dsCAsCzwbAEgeXcfBXx9q+AMW2n06WJnYeT2SWzwm7VoZLlMBPD8xE5bql [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string profileFile {
            get {
                return ResourceManager.GetString("profileFile", resourceCulture);
            }
        }
    }
}
