//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityControl.xUnit.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityControl.xUnit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] decryptedFile {
            get {
                object obj = ResourceManager.GetObject("decryptedFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] encryptedFile {
            get {
                object obj = ResourceManager.GetObject("encryptedFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NZrdyke9CJLmP/1o6eOtou0XbxUP5a5T1RaAnbgNQPW/Fyr2h3H1FKwYyixz8Wjbtd8m5nx52vxk4Yqs2btRcJilUXEi8H0Bj+ws3FymtGYpaq2l0XVViYrYOvpV5HiukYWuf/iD4AToFNt2n8WmY6aFbhS3nop10gAGzqZCIJuF8ZWcvaMSKl+Sfuv6MhffXnxHZQy6gjZca5TeGcmavhQXjhHFlWikBP5b5Y6j39b76Ccm5MW/REJBsgt6Z/RlS1vnc+6foTxh+lD57JKuc+0FCcPnbOBDayuJhOn0c4+4RgW97R3dl4f8+bBows+uoNSuXN7o5vZxcGYAQMuMTqr9QHztErl0q/CdGATgsReyIrhNLd2NSk1vENmyo14/BFgzswTvOACOurY2llEoumt/ENBBLzJC+7WiZ1FAd4geu0JDSx99f3e2TJxwCTpxkeX/BTWwtCZyzgbWWXxlKwxm9m/6MG9dYt1C94Ge3vceZL5M96kX68pnclmgq/Oy [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string profileFile {
            get {
                return ResourceManager.GetString("profileFile", resourceCulture);
            }
        }
    }
}
